apiVersion: v1
data:
  forward-input.conf: |-
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
  general.conf: |-
    # Prevent fluentd from handling records containing its own logs. Otherwise
    # it can lead to an infinite loop, when error in sending one message generates
    # another message which also fails to be sent and so on.
    <match fluentd.**>
      @type null
    </match>

    # Used for health checking
    <source>
      @type http
      port 9880
      bind 0.0.0.0
    </source>

    # Emits internal metrics to every minute, and also exposes them on port
    # 24220. Useful for determining if an output plugin is retryring/erroring,
    # or determining the buffer queue length.
    <source>
      @type monitor_agent
      bind 0.0.0.0
      port 24220
      tag fluentd.monitor.metrics
    </source>
  output.conf: |-
    <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level info
      include_tag_key true
      # Replace with the host/port to your Elasticsearch cluster.
      host "#{ENV['OUTPUT_HOST']}"
      port "#{ENV['OUTPUT_PORT']}"
      scheme "#{ENV['OUTPUT_SCHEME']}"
      ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
      logstash_format true
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
        queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
        overflow_action block
      </buffer>
    </match>
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>
kind: ConfigMap
metadata:
  labels:
    app: fluentd
    release: fluentd
  name: fluentd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluentd
    release: fluentd
  name: fluentd
spec:
  ports:
  - name: monitor-agent
    port: 24220
    protocol: TCP
    targetPort: 24220
  selector:
    app: fluentd
    release: fluentd
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: fluentd
    release: fluentd
  name: fluentd
spec:
  replicas: null
  selector:
    matchLabels:
      app: fluentd
      release: fluentd
  template:
    metadata:
      annotations:
        checksum/configmap: 9edc41dbed035b8b1de7377c9cb6aec2e51ebd1eac4e630be1d590ce7d50ac94
      labels:
        app: fluentd
        release: fluentd
    spec:
      containers:
      - env:
        - name: OUTPUT_HOST
          value: elasticsearch-client.default.svc.cluster.local
        - name: OUTPUT_PORT
          value: 8888
        - name: OUTPUT_SCHEME
          value: http
        - name: OUTPUT_SSL_VERSION
          value: TLSv1
        - name: OUTPUT_BUFFER_CHUNK_LIMIT
          value: 1M
        - name: OUTPUT_BUFFER_QUEUE_LIMIT
          value: 64
        image: gcr.io/google-containers/fluentd-elasticsearch:v2.4.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
            port: 9880
          initialDelaySeconds: 5
          timeoutSeconds: 1
        name: fluentd
        ports:
        - containerPort: 24220
          name: monitor-agent
          protocol: TCP
        - containerPort: 9880
          name: http-input
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /etc/fluent/config.d
          name: config-volume-fluentd
        - mountPath: /var/log/fluentd-buffers
          name: buffer
      volumes:
      - configMap:
          name: fluentd
        name: config-volume-fluentd
      - emptyDir: {}
        name: buffer
