apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: backups.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: Backup
    plural: backups
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: configs.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: Config
    plural: configs
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: deletebackuprequests.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: DeleteBackupRequest
    plural: deletebackuprequests
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: downloadrequests.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: DownloadRequest
    plural: downloadrequests
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: podvolumebackups.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: PodVolumeBackup
    plural: podvolumebackups
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: podvolumerestores.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: PodVolumeRestore
    plural: podvolumerestores
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: resticrepositories.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: ResticRepository
    plural: resticrepositories
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: restores.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: Restore
    plural: restores
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: schedules.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: Schedule
    plural: schedules
  scope: Namespaced
  version: v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: ark-hook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: ark-server
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    kubernetes.io/bootstrapping: rbac-defaults
    release: ark
  name: ark-hook
rules:
- apiGroups:
  - ark.heptio.com
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: ark-hook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ark-hook
subjects:
- kind: ServiceAccount
  name: ark-hook
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: ark-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ark-server
  namespace: default
---
apiVersion: v1
data:
  ark-config.yaml: "apiVersion: ark.heptio.com/v1\nkind: Config\nmetadata:\n  name:
    default\n\nbackupStorageProvider:\n  name: \n  bucket: \nbackupSyncPeriod: 60m\ngcSyncPeriod:
    60m\nscheduleSyncPeriod: 1m\nrestoreOnlyMode: false\n"
kind: ConfigMap
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: ark
---
apiVersion: v1
data: null
kind: Secret
metadata:
  labels:
    app: ark
    chart: ark-1.2.4
    heritage: Tiller
    release: ark
  name: ark
type: Opaque
