apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app: ark
    chart: ark-2.0.0
    heritage: Tiller
    release: ark
  name: backups.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: Backup
    plural: backups
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app: ark
    chart: ark-2.0.0
    heritage: Tiller
    release: ark
  name: configs.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: Config
    plural: configs
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app: ark
    chart: ark-2.0.0
    heritage: Tiller
    release: ark
  name: deletebackuprequests.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: DeleteBackupRequest
    plural: deletebackuprequests
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app: ark
    chart: ark-2.0.0
    heritage: Tiller
    release: ark
  name: downloadrequests.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: DownloadRequest
    plural: downloadrequests
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app: ark
    chart: ark-2.0.0
    heritage: Tiller
    release: ark
  name: podvolumebackups.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: PodVolumeBackup
    plural: podvolumebackups
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app: ark
    chart: ark-2.0.0
    heritage: Tiller
    release: ark
  name: podvolumerestores.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: PodVolumeRestore
    plural: podvolumerestores
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app: ark
    chart: ark-2.0.0
    heritage: Tiller
    release: ark
  name: resticrepositories.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: ResticRepository
    plural: resticrepositories
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app: ark
    chart: ark-2.0.0
    heritage: Tiller
    release: ark
  name: restores.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: Restore
    plural: restores
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app: ark
    chart: ark-2.0.0
    heritage: Tiller
    release: ark
  name: schedules.ark.heptio.com
spec:
  group: ark.heptio.com
  names:
    kind: Schedule
    plural: schedules
  scope: Namespaced
  version: v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ark
    release: ark
  name: ark-server
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: ark
    release: ark
  name: ark-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ark-server
  namespace: default
---
apiVersion: v1
data: null
kind: Secret
metadata:
  labels:
    app: ark
    release: ark
  name: ark
type: Opaque
---
apiVersion: ark.heptio.com/v1
backupStorageProvider:
  bucket: null
  name: null
backupSyncPeriod: 60m
gcSyncPeriod: 60m
kind: Config
metadata:
  labels:
    app: ark
    chart: ark-2.0.0
    heritage: Tiller
    release: ark
  name: default
restoreOnlyMode: false
scheduleSyncPeriod: 1m
