apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: backups.velero.io
spec:
  group: velero.io
  names:
    kind: Backup
    plural: backups
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: backupstoragelocations.velero.io
spec:
  group: velero.io
  names:
    kind: BackupStorageLocation
    plural: backupstoragelocations
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: deletebackuprequests.velero.io
spec:
  group: velero.io
  names:
    kind: DeleteBackupRequest
    plural: deletebackuprequests
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: downloadrequests.velero.io
spec:
  group: velero.io
  names:
    kind: DownloadRequest
    plural: downloadrequests
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: podvolumebackups.velero.io
spec:
  group: velero.io
  names:
    kind: PodVolumeBackup
    plural: podvolumebackups
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: podvolumerestores.velero.io
spec:
  group: velero.io
  names:
    kind: PodVolumeRestore
    plural: podvolumerestores
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: resticrepositories.velero.io
spec:
  group: velero.io
  names:
    kind: ResticRepository
    plural: resticrepositories
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: restores.velero.io
spec:
  group: velero.io
  names:
    kind: Restore
    plural: restores
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: schedules.velero.io
spec:
  group: velero.io
  names:
    kind: Schedule
    plural: schedules
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: serverstatusrequests.velero.io
spec:
  group: velero.io
  names:
    kind: ServerStatusRequest
    plural: serverstatusrequests
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: volumesnapshotlocations.velero.io
spec:
  group: velero.io
  names:
    kind: VolumeSnapshotLocation
    plural: volumesnapshotlocations
  scope: Namespaced
  version: v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: velero-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: velero-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: velero-server
  namespace: default
---
apiVersion: v1
data: null
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: velero
type: Opaque
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: default
spec:
  objectStorage:
    bucket: null
  provider: null
---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-2.3.1
  name: default
spec:
  provider: null
